// Generated by CoffeeScript 1.10.0
(function() {
  var Grid, Point, grid, pt;

  Point = (function() {
    function Point(x, y) {
      this.x = x;
      this.y = y;
    }

    Point.prototype.North = null;

    Point.prototype.NorthWest = null;

    Point.prototype.NorthEast = null;

    Point.prototype.East = null;

    Point.prototype.West = null;

    Point.prototype.South = null;

    Point.prototype.SouthWest = null;

    Point.prototype.SouthEast = null;

    return Point;

  })();

  Grid = (function() {
    function Grid(width, height) {
      this.width = width;
      this.height = height;
    }

    Grid.Points = [];

    return Grid;

  })();

  pt = new Point(15, 40);

  console.log(pt);

  grid = new Grid(15, 40);

  console.log(grid);

}).call(this);
